insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Afghanistan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Albania');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Algeria');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Andorra');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Angola');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Antigua & Deps');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Argentina');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Armenia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Australia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Austria');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Azerbaijan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Bahamas');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Bahrain');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Bangladesh');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Barbados');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Belarus');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Belgium');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Belize');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Benin');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Bhutan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Bolivia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Bosnia Herzegovina');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Botswana');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Brazil');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Brunei');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Bulgaria');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Burkina');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Burundi');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Cambodia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Cameroon');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Canada');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Cape Verde');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Central African Rep');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Chad');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Chile');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'China');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Colombia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Comoros');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Congo');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Congo {Democratic Rep}');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Costa Rica');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Croatia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Cuba');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Cyprus');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Czech Republic');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Denmark');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Djibouti');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Dominica');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Dominican Republic');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'East Timor');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Ecuador');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Egypt');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'El Salvador');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Equatorial Guinea');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Eritrea');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Estonia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Ethiopia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Fiji');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Finland');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'France');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Gabon');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Gambia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Georgia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Germany');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Ghana');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Greece');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Grenada');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Guatemala');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Guinea');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Guinea-Bissau');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Guyana');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Haiti');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Honduras');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Hungary');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Iceland');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'India');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Indonesia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Iran');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Iraq');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Ireland {Republic}');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Italy');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Ivory Coast');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Jamaica');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Japan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Jordan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Kazakhstan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Kenya');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Kiribati');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Korea North');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Korea South');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Kosovo');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Kuwait');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Kyrgyzstan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Laos');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Latvia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Lebanon');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Lesotho');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Liberia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Libya');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Liechtenstein');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Lithuania');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Luxembourg');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Macedonia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Madagascar');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Malawi');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Malaysia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Maldives');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Mali');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Malta');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Marshall Islands');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Mauritania');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Mauritius');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Mexico');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Micronesia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Moldova');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Monaco');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Mongolia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Montenegro');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Morocco');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Mozambique');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Myanmar, {Burma}');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Namibia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Nauru');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Nepal');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Netherlands');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'New Zealand');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Nicaragua');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Niger');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Nigeria');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Norway');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Oman');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Pakistan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Palau');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Panama');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Papua New Guinea');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Paraguay');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Peru');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Philippines');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Poland');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Portugal');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Qatar');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Romania');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Russian Federation');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Rwanda');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'St Kitts & Nevis');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'St Lucia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Saint Vincent & the Grenadines');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Samoa');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'San Marino');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Sao Tome & Principe');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Saudi Arabia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Senegal');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Serbia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Seychelles');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Sierra Leone');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Singapore');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Slovakia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Slovenia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Solomon Islands');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Somalia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'South Africa');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'South Sudan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Spain');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Sri Lanka');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Sudan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Suriname');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Swaziland');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Sweden');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Switzerland');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Syria');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Taiwan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Tajikistan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Tanzania');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Thailand');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Togo');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Tonga');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Trinidad & Tobago');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Tunisia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Turkey');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Turkmenistan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Tuvalu');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Uganda');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Ukraine');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'United Arab Emirates');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'United Kingdom');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'United States');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Uruguay');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Uzbekistan');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Vanuatu');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Vatican City');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Venezuela');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Vietnam');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Yemen');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Zambia');
insert into oj.country(oj.country.country_id , oj.country.country_name )        values(oj.country_id_seq.nextval , 'Zimbabwe');
